### Test GET /api
GET http://localhost:5000/api
Accept: application/json

### Test User Signup (POST /user/signup)
POST http://localhost:5000/user/signup
Content-Type: application/json

{
  "name": "John Doe",
  "username": "johdoe",
  "email": "johndoe@examp]le.com",
  "password": "securepassword"
}

### Test User Login (POST /user/login)
POST http://localhost:5000/user/login
Content-Type: application/json

{
  "username": "yogi",
  "password": "1234"
}

### Test Get All Users (GET /user/all)
GET http://localhost:5000/user/all
Accept: application/json

### Test User Logout (POST /user/logout)
POST http://localhost:5000/user/logout
Content-Type: application/json
